version: "2"
services:
  app:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mysql
    - mongo
  mysql:
    image: mysql
    environment:
      NAME: backend-demo
      HOST: localhost
      USERNAME: root
      PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
    - "3306:3306"
  mongo:
    image: mongo
    environment:
      NAME: backend-demo
      HOST: localhost
    ports:
    - "27017:27017"