version: "3"

services:
  app:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mysql
    entrypoint: ["./wait.sh"]
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "33000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
