version: '3.3'

services:

    node:
        build: ./node
        volumes:
            - ../:/opt/app
        tty: true
        links:
            - mysql
            - mongo

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=backend_demo
                # - MYSQL_USER=root
                - MYSQL_PASSWORD=password
                - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./data/mysql/:/var/lib/mysql
        expose:
            - "3306"

    mongo:
        build: ./mongo
        expose:
            - "27017"
        # volumes:
        #     - ./data/mongo/:/var/lib/mongodb

    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
            - ./certbot/certs/:/var/certs
        ports:
            - "80:80"
            - "443:443"
        tty: true

    apache:
        build:
            context: ./apache
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/apache/:/usr/local/apache2/logs
            - ./certbot/certs/:/var/certs
        ports:
            - "80:80"
            - "443:443"
        tty: true

    certbot:
        build:
            context: ./certbot
        links:
            - apache
            - nginx
        volumes:
          - ./certbot/letsencrypt/:/var/www/letsencrypt
          - ./certbot/certs/:/var/certs

    
    
