version: '3.3'

services:

    node:
        build: ./node
            # args:
            #     - NODE_VERSION=latest
            #     - PROJECT_PATH=/opt/app/
            #     - NODE_ENV=production
            #     - YARN=false
        volumes:
            - ../:/opt/app
        # entrypoint: run-nodock "node index.js"
        tty: true
        depends_on:
                - mysql
                - mongo

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=backend-demo
                # - MYSQL_USER=root
                - MYSQL_PASSWORD=password
                - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./data/mysql/:/var/lib/mysql
        expose:
            - "3306"

    mongo:
        build: ./mongo
        restart: always
        expose:
            - "27017"
        volumes:
            - ./data/mongo/:/var/lib/mongodb

    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
            - ./certbot/certs/:/var/certs
        ports:
            - "80:80"
            - "443:443"
        tty: true

    apache:
        build:
            context: ./apache
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/apache/:/usr/local/apache2/logs
            - ./certbot/certs/:/var/certs
        ports:
            - "80:80"
            - "443:443"
        tty: true

    certbot:
        build:
            context: ./certbot
        links:
            - apache
            - nginx
        volumes:
          - ./certbot/letsencrypt/:/var/www/letsencrypt
          - ./certbot/certs/:/var/certs

    workspace:
        build:
            context: ./workspace
            args:
                - NODE_VERSION=latest
                - TZ=UTC
        links:
            - nginx
        volumes:
            - ../:/opt/app

    memcached:
        build:
            context: ./memcached
        expose:
            - "11211"

    redis:
        build:
            context: ./redis
        expose:
            - "6379"
        volumes:
            - ./data/redis:/data
