version: "3.5"
services:
  app:
    build: .
    networks:
     - nginx_network
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mongo
  mongo:
    image: mongo
    networks:
     - nginx_network
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/:/var/lib/mongodb
  
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=backend_demo
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    networks:
     - nginx_network
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"

#   nginxproxy:
#     build:
#       context: ./nginx
#     container_name: nginxproxy
#     networks:
#      - nginx_network
#     restart: always
#     expose:
#      - 80
#     ports:
#       - "443:443"
#       - "80:80"
#     environment:
#       DOMAIN: mySiteaddress.com
#       EMAIL: myMail@hotmail.com
#       RENEW_INTERVAL: 12h
#     volumes:
#       - ./certificates:/usr/share/nginx/certificates
#       - ./default.conf:/etc/nginx/conf.d/default.conf
# networks:
#    nginx_network:
#      driver: bridge
  


  # mysql:
  #   build:
  #     context: ./mysql
  #     args:
  #     - MYSQL_DATABASE=backend_demo
  #     - MYSQL_USER=root
  #     - MYSQL_ROOT_PASSWORD=password
  #   volumes:
  #   - ./data/mysql/:/var/lib/mysql
  #   expose:
  #   - "3306"
  # mongo:
  #   build: ./mongo
  #   expose:
  #   - "27017"
  #   volumes:
  #   - ./data/mongo/:/var/lib/mongodb
  # mysql:
  #   image: mysql
  #   environment:
  #     NAME: backend-demo
  #     HOST: localhost
  #     USERNAME: root
  #     PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/:ro
  #   ports:
  #   - "3306:3306"